apiVersion: v1
kind: Pod
metadata: 
  name: env
  labels:
    purpose: env-demo
    env: dev
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: course
        value: "kubernetes"
      - name: project
        value: "roboshop"