apiVersion: v1
kind: Pod
metadata:
  name: podsecret
  labels:
    project: roboshop
    env: dev 
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
     - secretRef:
        name: secret
