apiVersion: v1
kind: Service
metadata:
  name: clusterip 
  labels: 
    project: roboshop
    purpose: demo
    env: dev
spec:
  selector:
    project: roboshop
    purpose: demo
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod
  labels:
    project: roboshop
    purpose: demo
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx